### ISSUE TITLE
[FE] 메인페이지 추천 리스트 레이아웃을 구현한다

### ISSUE THREAD

**Issue by hyewon29** [Fancy96/useless-coin-pick#7]
## ✍🏻구현할 기능

> 구현할 기능에 대해 설명해 주세요.

* main에 코인 추천리스트 레이아웃을 구현한다

## 🎤 세부 작업 내용

* [ ] 슬롯 머신 안에 외부 박스를 한개 만들고, 안에 내부 박스 3개를 div로 선언하여 만든다.
* [ ] 각 영역을 구분짓기 위해 우선, 색깔로 표시한다.

## 📚참고 자료

*

**Comment by Fancy96** [comment]
슬롯머신 구현하시느라 고생하셨습니다!
